# Generated by Django 5.0 on 2025-04-28 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='about',
            field=models.TextField(blank=True, default='No information provided.'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='club_position',
            field=models.CharField(blank=True, default='Member', max_length=100),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='member_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='member_type',
            field=models.CharField(choices=[('advisor', 'Advisor'), ('committee', 'Committee'), ('general', 'General Member'), ('alumni', 'Alumni'), ('executive', 'Executive')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='skills',
            field=models.TextField(blank=True, default='No skills listed.'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
