# Generated by Django 5.0 on 2025-04-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='Name of the website', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Upload the website logo', null=True, upload_to='logos/')),
                ('about_text', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('social_media_links', models.JSONField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
